### ISSUE TITLE
AVI files won't play after SEQ import

### ISSUE THREAD

**Issue by BRHacks** [gtatters/ThermImageJ#10]
**Describe the bug**
After running the Import SEQ macro on Windows 10 x64, an error occurs.

**To Reproduce**
1. Import an SEQ using the macro
2. See error

**Expected behavior**
Expected the resulting avi to appear within ImageJ for manipulation

**Screenshots**
![image](https://user-images.githubusercontent.com/117801804/200749460-53c0dab3-b3eb-4f90-82d6-6178ae3ec3ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by gtatters** [comment]
Errors that FIJI kicks back aren't always that helpful but have you installed the FFMPEG plugin within FIJI itself?  The error seems to indicate that it cannot find that macro/plugin.

Alternatively (most commonly) is a problem with the file itself, corrupted or collected by a different version of flir software.  Could you share a sample .seq file or verify you get the same error using the .seq file I have shared on this repository.
