### ISSUE TITLE
import optical layer as well

### ISSUE THREAD

**Issue by akohlsmith** [gtatters/ThermImageJ#11]
The .jpg files have both optical and thermal images in them; I can use the flir tools to see them both.

is there any way to import both images and be able to overlay one or is this outside of what ImageJ and/or ThermImageJ could do?

**Comment by gtatters** [comment]
Sorry but ThermimageJ is only designed to pull out the thermal data from the jpgs.  The exiftool program might be able to do this, but you would want to look at https://exiftool.org to see how to extract mulitple images from the single flir jpg.
