### ISSUE TITLE
opening CSQ files

### ISSUE THREAD

**Issue by oseynnes** [gtatters/ThermImageJ#3]
**Describe the bug**
When I try to open a .csq file I get the following error message:
"Error:		
Index (0) out of 0--1 range in line 1360:
print ( perl + perlsplit + "-i " + tempfolder + File . separator + fff_files [ 0 <]> + " -o " + filedir + File . separa..."

**To Reproduce**
1. FILE>IMPORT FLIR CSQ
2. select file
3. log window output:
------ Running ConvertFLIRVideo function ------
Loading:  /Users/me/data_analysis/thermal_analysis/data/test_file.csq
Extracting calibration and image settings

------ Running flirvalues function ------
Extracted Camera Calibration and Object Parameters:
13631.7040, 1369.7000, 1, -3833, 0.0105, 0, 0, 0.0032, 0.0032, 0.7320, 0.9500, 1, 20, 20, 20, 1, 50, 464, 348

Splitting the video file into its .fff files with: 
/usr/bin/perl /Users/me/data_analysis/thermal_analysis/scripts/split.pl -i /Users/me/data_analysis/thermal_analysis/data/test_file.csq -o /Users/me/data_analysis/thermal_analysis/data/temp -b frame -p fff -x fff
Splitting fff files into jpegls files by looping through all files similar to:

**Expected behavior**
Opening the file

**Desktop (please complete the following information):**
- MacOS Catalina 10.15.3
- perl v5.18.4 built for darwin-thread-multi-2level

**Comment by gtatters** [comment]
are you getting this error running the sample csq I provide?  https://github.com/gtatters/ThermImageJ/blob/master/SampleFiles.zip

It is possible that my perl split script needs adjusting for your file type.  I could take a look at a sample file of yours if you are able to send it to me?

**Comment by oseynnes** [comment]
Thank you. Yes, I get the same error message. Could it come from an installation problem? I am happy to send you my file if you want. At this address?


On 12 Mar 2020, at 11:45, Glenn Tattersall <notifications@github.com<mailto:notifications@github.com>> wrote:



are you getting this error running the sample csq I provide? https://github.com/gtatters/ThermImageJ/blob/master/SampleFiles.zip

It is possible that my perl split script needs adjusting for your file type. I could take a look at a sample file of yours if you are able to send it to me?

**Comment by gtatters** [comment]
ok.  so, that suggests an install problem, so sending me file might not help yet.  Can you verify whether the split.pl script was copied to your FIJI/scripts folder, according to the (brief) instructions.

**Comment by oseynnes** [comment]
Yes, the split.pl file is in Fiji/scripts. Perhaps something that I need to change in the split script?

On 12 Mar 2020, at 11:57, Glenn Tattersall <notifications@github.com<mailto:notifications@github.com>> wrote:



ok. so, that suggests an install problem, so sending me file might not help yet. Can you verify whether the split.pl script was copied to your FIJI/scripts folder, according to the (brief) instructions.

**Comment by gtatters** [comment]
and the installation checks?  did they produce errors?  I'd need to know that exiftool, perl and ffmpeg are installed properly.

**Comment by gtatters** [comment]
I haven't tested on Catalina yet (I've been delaying the update to get bugs out of the os), but I doubt that is the issue.  Unfortunately, I won't update to Catalina until the end of semester to avoid sudden loss of function during teaching.  Hopefully I can diagnose the problem one error at a time.

**Comment by gtatters** [comment]
Hmm..i just noticed in your error message that FIJI seems to think that the split.pl is in a different subfolder than Fiji/scripts.  But on line 57 of the toolset, I know I scan for where your ImageJ folder is.  Can you confirm the precise path location of your FIJI install?  I would advise you place FIJI in a folder that you have read+write permission.  Usually on a Mac, FIJI goes directly in the Application folder:

i.e.
/Applications/FIJI

thus, the scripts would be:
/Applications/FIJI/scripts

I don't know if this will affect functionality or not.

**Comment by oseynnes** [comment]
It now works! I had made a mistake for the line "var perlscriptpath=getDirectory("imageJ") + "scripts" + File.separator;”. I thought that I should replace “imageJ” by “Fiji”. I have now set the directory address with “imageJ” and it works. Thank you for your help.

On 12 Mar 2020, at 13:35, Glenn Tattersall <notifications@github.com<mailto:notifications@github.com>> wrote:



Hmm..i just noticed in your error message that FIJI seems to think that the split.pl is in a different subfolder than Fiji/scripts. But on line 57 of the toolset, I know I scan for where your ImageJ folder is. Can you confirm the precise path location of your FIJI install? I would advise you place FIJI in a folder that you have read+write permission. Usually on a Mac, FIJI goes directly in the Application folder:

i.e.
/Applications/FIJI

thus, the scripts would be:
/Applications/FIJI/scripts

I don't know if this will affect functionality or not.

**Comment by gtatters** [comment]
Aha!  FIJI is Just ImageJ.  The circular acronym doesn't really help!  Glad you figured it out, because I would not have known.  

I do need to add some error checking for file/folder executions and some more informative error messages. Eventually I'll have that up in the install instructions.  

Thanks for filing the issue.  At least I'll know what trips users up.

**Comment by oseynnes** [comment]
I have used Fiji for a long time, it was a stupid mistake. Thanks again for your support and for sharing this great plugin.

Le 12 mars 2020 à 16:29, Glenn Tattersall <notifications@github.com> a écrit :

﻿

Aha! FIJI is Just ImageJ. The circular acronym doesn't really help! Glad you figured it out, because I would not have known.

I do need to add some error checking for file/folder executions and some more informative error messages. Eventually I'll have that up in the install instructions.

Thanks for filing the issue. At least I'll know what trips users up.

**Comment by oseynnes** [comment]
On a separate note. I am dealing with moving objects (human movement) and it would be nice to be able to run the analysis on distinct ROIs associated with each image of the sequence (currently it seems that the same ROI is applied to all images).
Another nice feature would have been the possibility to automatically save ROIs based on temperature threshold. This would be useful for the above point but also to analyse sub-areas of changing temperature.

I did not fill these in as request for new features on Github as they have nothing to do with the function of the plugin as it is designed, but just in case ;)


On 12 Mar 2020, at 16:29, Glenn Tattersall <notifications@github.com<mailto:notifications@github.com>> wrote:



Aha! FIJI is Just ImageJ. The circular acronym doesn't really help! Glad you figured it out, because I would not have known.

I do need to add some error checking for file/folder executions and some more informative error messages. Eventually I'll have that up in the install instructions.

Thanks for filing the issue. At least I'll know what trips users up.

**Comment by gtatters** [comment]
I would like that as well!  With colleagues, outside of this software, we are trying to get Machine learning roi coding working, but it won't likely be part of ThermimageJ.  Early days yet for that.

But at least you can use ThermimageJ to extract  or convert CSQ files into a format where you might do that in another environment.  

As for ROI saving...that seems like some kind of feature that ImageJ might already have, but I know what you mean.  That is probably beyond my skills for the time being.  You could probably use ImageJ masking features to remove all parts of the image space that are below or above your threshold temperature.  I am less likely to develop those features, much as they would be nice to have!

**Comment by gtatters** [comment]
in terms of a moving ROI...there are Tracker or Tracking plugins that you might be able to get to work that are available in FIJI.  Once you have the ROIs registered, I think those plugins allow you to extract certain types of info like mean, max or median intensity scores (which would be temperature if you ran the conversions).

**Comment by oseynnes** [comment]
Yes, I am looking into this. Thank you again.


On 12 Mar 2020, at 19:40, Glenn Tattersall <notifications@github.com<mailto:notifications@github.com>> wrote:



in terms of a moving ROI...there are Tracker or Tracking plugins that you might be able to get to work that are available in FIJI. Once you have the ROIs registered, I think those plugins allow you to extract certain types of info like mean, max or median intensity scores (which would be temperature if you ran the conversions).
