### ISSUE TITLE
ThermalImageJ says image type not recognized

### ISSUE THREAD

**Issue by shojajm** [gtatters/ThermImageJ#4]
Hi there. I am currently trying to use your ThermImageJ plugin to import a thermal image and have been recieving this error -- --

"Warning -- Raw Thermal Type Unknown. This file might not be a radiometric JPG.
Setting Raw Thermal Type to tiff and attempting conversion. If resulting file is 0 bytes, the jpg cannot be converted.
Examine the settings on your camera to ensure radiometric jpgs are being saved.
Raw Thermal Type: tiff
Converting 02 C1.jpg to 02C1.tif

FLIR JPG files converted into tiff format. Import these and convert to temperature using the Raw2Temp macro.

Use the File->Import->Image Sequence function to load in images
Some images may require that the pixel byte order be swapped. Use the Byte Swapper plugin after importing if necessaary
Done"

How can I check to see if the image is a radiometric JPG and furthermore if it is what is causing the issue?
Thank you.

**Comment by gtatters** [comment]
Use the exiftool command line tool to scan the file for FLIR parameters.  Or check how you are saving your images with your camera.  Or contact FLIR to ask them whether the model you are using saves a radiometric image.

**Comment by gtatters** [comment]
attach your jpg and I can look at it.  there isn't a quick solution to scan files since that depends entirely on how FLIR manages their files.  see https://github.com/gtatters/Thermimage/issues/7

**Comment by gtatters** [comment]
or https://github.com/gtatters/Thermimage/issues/10

**Comment by shojajm** [comment]
Thank you so much for your time. We are most grateful. We used a SEEK compact camera I phone. Here is one of the thermal images.
![02 C1](https://user-images.githubusercontent.com/71300616/102951197-1ba1f180-4481-11eb-88c0-a74364f0b7e0.jpg)

**Comment by gtatters** [comment]
No idea what that camera is, but as i commented in the other issues above, if this is a consumer grade thermal cam, it can't be used with thermimage.  FLIR likely suppresses saving the raw data to these files.  They want you to buy more pricey devices.

**Comment by gtatters** [comment]
Output from exiftool scanning the file below, nothing in here shows me any raw data or planck constants are in the file, ergo it is not a radiometric jpg.

> ExifTool Version Number         : 11.62
File Name                       : image.jpg
Directory                       : .
File Size                       : 96 kB
File Modification Date/Time     : 2020:12:22 21:12:54-05:00
File Access Date/Time           : 2020:12:22 21:12:54-05:00
File Inode Change Date/Time     : 2020:12:22 21:13:01-05:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 72
Y Resolution                    : 72
Exif Byte Order                 : Big-endian (Motorola, MM)
Image Description               : Taken with iPhone 6S (GSM+CDMA),iOS 11.4
Make                            : Seek Thermal, Inc.
Camera Model Name               : Compact, HW v7 TH:v2 TLID:v0
Orientation                     : Rotate 90 CW
Software                        : Seek Thermal App 2.1.6.2,SDK 2.1.6.0,FW 1.3.0.0,IP 2.5.3.10
Modify Date                     : 2018:11:02 22:57:21
Date/Time Original              : 2018:11:02 22:57:21
Create Date                     : 2018:11:02 22:57:21
User Comment                    : SeekwareBlendModeNone
Color Space                     : sRGB
Exif Image Width                : 640
Exif Image Height               : 480
Digital Zoom Ratio              : 1
Serial Number                   : 171280LM91A3
XMP Toolkit                     : XMP Core 5.4.0
Creator Tool                    : Seek Thermal App 2.1.6.2,SDK 2.1.6.0,FW 1.3.0.0,IP 2.5.3.10
Description                     : Taken with iPhone 6S (GSM+CDMA),iOS 11.4
Current IPTC Digest             : 1a6097cd6ed30bca400699bc55d5b82c
Coded Character Set             : UTF8
Application Record Version      : 2
Digital Creation Time           : 22:57:21
Digital Creation Date           : 2018:11:02
Caption-Abstract                : Taken with iPhone 6S (GSM+CDMA),iOS 11.4
Date Created                    : 2018:11:02
Time Created                    : 22:57:21
IPTC Digest                     : 1a6097cd6ed30bca400699bc55d5b82c
Image Width                     : 640
Image Height                    : 480
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 640x480
Megapixels                      : 0.307
Date/Time Created               : 2018:11:02 22:57:21
Digital Creation Date/Time      : 2018:11:02 22:57:21

**Comment by shojajm** [comment]
Okay, thank you. Do you know of any other ways that this type of image can be thermally calibrated?

**Comment by gtatters** [comment]
Sorry I do not.  At least if you worked with grayscale, you would could attempt a manual mapping of temperature to colour, but the accuracy of the camera is probably really poor otherwise there would be raw data within it, with the calibration constants for your sensor.  Each sensor needs to be calibrated at the manufacturer.

**Comment by shojajm** [comment]
Okay. Thank you again!

**Comment by gtatters** [comment]
double check if there isn't another setting to save true radiometric jpgs in the camera.  Otherwise, you could import it as a normal greyscale jpg into ImageJ and manually re-map the grey values to the min and max temperatures shown.  I don't think it will be very accurate and would not be compatible with other calculations in my macros/tools.
