### ISSUE TITLE
Error: "Index (-1) is outside of the 0--1 range in line 2499:"

### ISSUE THREAD

**Issue by coatej** [gtatters/ThermImageJ#6]
I'm new to much of this, so apologies if I'm missing something simple. I've just gone through the install instructions, and am now trying to load a thermal image from my FLIR camera into ImageJ using ThermImageJ. When I try to "Import FLIR JPG" I get the following macro error. This occurs with my FLIR photos, as well as the two sample jpgs provided with ThermImageJ-master. 
![image](https://user-images.githubusercontent.com/90599246/133197046-010b3ac5-bf0e-448c-aa5f-aad036703fc9.png)
[Debug.csv](https://github.com/gtatters/ThermImageJ/files/7158960/Debug.csv)

Any thoughts? Thanks in advance!!

**Comment by gtatters** [comment]
that error usually means that when exiftool scans your file, it cannot find any calibration constants and it often happens when using a non-radiometric jpg.  But it might also happen if you haven't changed the paths to the various installs.  Have you edited the ThermimageJ.ijm file to reflect where exiftool, ffmpeg, perl are all installed?   

Did you perform all the installation checks?

**Comment by coatej** [comment]
I suspect this could be where I'm going wrong, as I'm not sure that I've correctly/completely edited the .ijm file despite my best efforts. The below screenshot shows the edits I made to the .ijm file
![image](https://user-images.githubusercontent.com/90599246/133355977-ba8c9b43-0ce5-4b4c-9b51-e68824d04594.png).

I've done my best to perform installation checks, but I'm not certain I've done this properly. Particularly with regards to editing the .ijm file. The first few processes in Command Prompt worked just as you show in your installation video though.

**Comment by gtatters** [comment]
I would recommend you install these programs in the folders that were in the default .ijm file, or independently verify that they are not being blocked by windows security features.  It really looks like you've installed them all in the wrong folders and especially exiftool needs to follow the instructions on the exiftool website to function cleanly.  Sorry, I can't troubleshoot these features.  It's assumed the user knows how to use some command line operations.  

Screenshots of anything or everything (errors or demonstration that simply running things at the command line do or do not work) would help if you need further assistance.  

eg. 

type into command line and give us the output:

`exiftool NameOfYourJpg.jpg`
